export default {

  alexavatar: require('../assets/images&videos/alexavatar.jpg'),
  annou: require('../assets/images&videos/annou.png'),
  Arroo: require('../assets/images&videos/Arroo.png'),
  back: require('../assets/images&videos/back.png'),
  bellicon: require('../assets/images&videos/bellicon.png'),
  calander: require('../assets/images&videos/calander.png'),
  check: require('../assets/images&videos/check.png'),
  checkbox: require('../assets/images&videos/checkbox.png'),
  checked: require('../assets/images&videos/checked.png'),
  checkimg: require('../assets/images&videos/checkimg.png'),
  church: require('../assets/images&videos/church.png'),
  circleplus: require('../assets/images&videos/circleplus.png'),
  close: require('../assets/images&videos/close.png'),
  comment: require('../assets/images&videos/comment.png'),
  delete: require('../assets/images&videos/delete.png'),
  editblack: require('../assets/images&videos/editblack.png'),
  equalizer: require('../assets/images&videos/equalizer.png'),
  eyeclose: require('../assets/images&videos/eyeclose.png'),
  eyeopen: require('../assets/images&videos/eyeopen.png'),
  facebook: require('../assets/images&videos/facebook.png'),
  filter: require('../assets/images&videos/filter.png'),
  google: require('../assets/images&videos/google.png'),
  hamburger: require('../assets/images&videos/hamburger.png'),
  home: require('../assets/images&videos/home.png'),
  left_arrow: require('../assets/images&videos/left_arrow.png'),
  notification: require('../assets/images&videos/notification.png'),
  pause: require('../assets/images&videos/pause.png'),
  play: require('../assets/images&videos/play.png'),
  plus: require('../assets/images&videos/plus.png'),
  profile: require('../assets/images&videos/profile.png'),
  radio: require('../assets/images&videos/radio.png'),
  radiofill: require('../assets/images&videos/radiofill.png'),
  Recci: require('../assets/images&videos/Recci.png'),
  right_arrow: require('../assets/images&videos/right_arrow.png'),
  scanner: require('../assets/images&videos/scanner.png'),
  search: require('../assets/images&videos/search.png'),
  Splash: require('../assets/images&videos/Splash.png'),
  uploadlogo: require('../assets/images&videos/uploadlogo.png'),

};
